In [47]:
%matplotlib inline
from math import e
import math
import numpy as np

## Regularization with Weight Decay

In [7]:
in_dta = np.loadtxt('in.dta')
out_dta = np.loadtxt('out.dta')

In [11]:
in_dta[:5], out_dta[:5]

(array([[-0.77947021,  0.83822138,  1.        ],
        [ 0.15563491,  0.89537743,  1.        ],
        [-0.0599077 , -0.71777995,  1.        ],
        [ 0.20759636,  0.75893338,  1.        ],
        [-0.19598312, -0.37548716, -1.        ]]),
 array([[-0.10600562, -0.08146703, -1.        ],
        [ 0.17792951, -0.34595141, -1.        ],
        [ 0.10216153,  0.71825825,  1.        ],
        [ 0.69407831,  0.62339743, -1.        ],
        [ 0.02354107,  0.72743221,  1.        ]]))

In [32]:
x_in = np.append(np.ones((len(in_dta),1)), in_dta[:,:2], axis=1)
y_in = in_dta[:,2]
x_in[:5], y_in[:5]

(array([[ 1.        , -0.77947021,  0.83822138],
        [ 1.        ,  0.15563491,  0.89537743],
        [ 1.        , -0.0599077 , -0.71777995],
        [ 1.        ,  0.20759636,  0.75893338],
        [ 1.        , -0.19598312, -0.37548716]]),
 array([ 1.,  1.,  1.,  1., -1.]))

In [33]:
x_out = np.append(np.ones((len(out_dta),1)), out_dta[:,:2], axis=1)
y_out = out_dta[:,2]
x_out[:5], y_out[:5]

(array([[ 1.        , -0.10600562, -0.08146703],
        [ 1.        ,  0.17792951, -0.34595141],
        [ 1.        ,  0.10216153,  0.71825825],
        [ 1.        ,  0.69407831,  0.62339743],
        [ 1.        ,  0.02354107,  0.72743221]]),
 array([-1., -1.,  1., -1.,  1.]))

In [77]:
lin_reg = lambda x,y: np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y)
class_err = lambda r,y: 1 - len(r[r == y]) / len(r)

In [44]:
lin_reg(x_in, y_in)

array([ 0.14083789, -0.12469201,  0.14959674])

In [50]:
trans = lambda x: [1,x[0],x[1],x[0]*x[0],x[1]*x[1],x[0]*x[1],np.abs(x[0]-x[1]),np.abs(x[0]+x[1])]

In [53]:
z_in = np.apply_along_axis(trans, 1, in_dta)
w_lin = lin_reg(z_in, y_in)
w_lin

array([-1.64706706, -0.14505927,  0.10154121, -2.03296844, -1.82804373,
        2.48152945,  4.15893861,  0.31651714])

In [78]:
z_in_result = np.sign(z_in.dot(w_lin))
#1 - len(z_in_result[z_in_result == y_in]) / len(z_in_result)
class_err(z_in_result, y_in)

0.02857142857142858

In [79]:
z_out = np.apply_along_axis(trans, 1, out_dta)
z_out_result = np.sign(z_out.dot(w_lin))
#1 - len(z_out_result[z_out_result == y_out]) / len(z_out_result)
class_err(z_out_result, y_out)

0.08399999999999996

In [95]:
10**-3

0.001

In [94]:
z_in.T.dot(z_in) + np.identity(z_in.shape[1]) * 0.003

array([[  3.50030000e+01,   3.24728985e+00,   3.17911270e+00,
          1.18166779e+01,   1.24501605e+01,  -2.32118150e+00,
          2.61821824e+01,   2.03715598e+01],
       [  3.24728985e+00,   1.18196779e+01,  -2.32118150e+00,
          1.29844813e+00,   1.70886992e-02,   1.50139990e+00,
          8.81263043e-01,   3.83874727e+00],
       [  3.17911270e+00,  -2.32118150e+00,   1.24531605e+01,
          1.50139990e+00,   2.76557867e+00,   1.70886992e-02,
          3.17283139e+00,   3.49066303e+00],
       [  1.18166779e+01,   1.29844813e+00,   1.50139990e+00,
          7.56895595e+00,   4.53119818e+00,  -1.30210166e+00,
          1.14215986e+01,   7.76352565e+00],
       [  1.24501605e+01,   1.70886992e-02,   2.76557867e+00,
          4.53119818e+00,   6.69679602e+00,  -1.36229558e+00,
          1.14543114e+01,   8.04284885e+00],
       [ -2.32118150e+00,   1.50139990e+00,   1.70886992e-02,
         -1.30210166e+00,  -1.36229558e+00,   4.53419818e+00,
         -7.21144505e+00,   3.7

In [96]:
lin_w_reg = lambda x,k,y: np.linalg.inv(x.T.dot(x) + np.identity(x.shape[1]) * (10**k)).dot(x.T).dot(y)

In [98]:
w_reg_n3 = lin_w_reg(z_in, -3, y_in)
w_reg_n3

array([-1.6432827 , -0.14333537,  0.10144329, -2.02456533, -1.81721505,
        2.45550685,  4.14009201,  0.31960135])

In [99]:
z_in_result = np.sign(z_in.dot(w_reg_n3))
class_err(z_in_result, y_in)

0.02857142857142858

In [100]:
z_out_result = np.sign(z_out.dot(w_reg_n3))
class_err(z_out_result, y_out)

0.07999999999999996

In [101]:
w_reg_3 = lin_w_reg(z_in, 3, y_in)
z_in_result = np.sign(z_in.dot(w_reg_3))
print("E_in", class_err(z_in_result, y_in))
z_out_result = np.sign(z_out.dot(w_reg_3))
print("E_out", class_err(z_out_result, y_out))

E_in 0.37142857142857144
E_out 0.43600000000000005


In [104]:
for k in [2,1,0,-1,-2]:
    w = lin_w_reg(z_in, k, y_in)
    z_out_result = np.sign(z_out.dot(w))
    print(k, class_err(z_out_result, y_out))

2 0.22799999999999998
1 0.124
0 0.09199999999999997
-1 0.05600000000000005
-2 0.08399999999999996


## Regularization for Polynomials