In [1]:
%matplotlib inline
import numpy as np
from sklearn import svm

## 1. [d]

# Polynomial Kernels

In [2]:
train = np.loadtxt('features.train')
test = np.loadtxt('features.test')

In [55]:
train[:,1:][:3], train[:,0][:3], np.unique(train[:,0])

(array([[ 0.3410918 , -4.5289375 ],
        [ 0.44413086, -5.4968125 ],
        [ 0.23100195, -2.88675   ]]),
 array([ 6.,  5.,  4.]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [61]:
train[:,0][:13] == 0

array([False, False, False, False, False, False, False, False,  True,
       False, False,  True, False], dtype=bool)

In [29]:
clf = svm.SVC(C=0.01, decision_function_shape='ovr', kernel='poly', degree=2, gamma=1, coef0=1)
clf.fit(train[:,1:], train[:,0])

SVC(C=0.01, cache_size=200, class_weight=None, coef0=1,
  decision_function_shape='ovr', degree=2, gamma=1, kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [63]:
clf0 = svm.SVC(C=0.01, decision_function_shape='ovr', kernel='poly', degree=2, gamma=1, coef0=1)
clf0.fit(train[:,1:], train[:,0]==0)

SVC(C=0.01, cache_size=200, class_weight=None, coef0=1,
  decision_function_shape='ovr', degree=2, gamma=1, kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [68]:
1 - (clf0.predict(train[:,1:]) == (train[:,0] == 0)).sum() / len(train)

0.10588396653408316

In [75]:
clf0.n_support_

array([1090, 1089], dtype=int32)

In [76]:
for o in range(0,9,2):
    clf = svm.SVC(C=0.01, decision_function_shape='ovr', kernel='poly', degree=2, gamma=1, coef0=1)
    clf.fit(train[:,1:], train[:,0]==o)
    e_in = 1 - (clf.predict(train[:,1:]) == (train[:,0] == o)).sum() / len(train)
    print(o, e_in, clf.n_support_)

0 0.105883966534 [1090 1089]
2 0.100260595254 [1239  731]
4 0.0894253188863 [1204  652]
6 0.0910711836511 [1229  664]
8 0.0743382252092 [1234  542]


## ^^^ 2. [a]

In [77]:
for o in range(1,10,2):
    clf = svm.SVC(C=0.01, decision_function_shape='ovr', kernel='poly', degree=2, gamma=1, coef0=1)
    clf.fit(train[:,1:], train[:,0]==o)
    e_in = 1 - (clf.predict(train[:,1:]) == (train[:,0] == o)).sum() / len(train)
    print(o, e_in, clf.n_support_)

1 0.0144013166918 [193 193]
3 0.0902482512687 [1292  658]
5 0.0762584007681 [1029  556]
7 0.0884652311068 [1059  645]
9 0.0883280757098 [1334  644]


## ^^^ 3. [a]

In [160]:
(1090 + 1089) - (193 + 193)

1793

## ^^^ 4. [c]

In [97]:
train[:,0][:40][train[:,0][:40]==1], train[:,0][:40][train[:,0][:40]==5]

(array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.]), array([ 5.,  5.]))

In [3]:
train_x_1_5 = np.concatenate((train[:,1:][train[:,0]==1], train[:,1:][train[:,0]==5]))
train_y_1_5 = np.concatenate((train[:,0][train[:,0]==1], train[:,0][train[:,0]==5]))
train_x_1_5[:3], train_y_1_5[:3]

(array([[ 0.12304297, -0.707875  ],
        [ 0.11385937, -0.931375  ],
        [ 0.11537109, -0.386     ]]), array([ 1.,  1.,  1.]))

In [4]:
test_x_1_5 = np.concatenate((test[:,1:][test[:,0]==1], test[:,1:][test[:,0]==5]))
test_y_1_5 = np.concatenate((test[:,0][test[:,0]==1], test[:,0][test[:,0]==5]))
test_x_1_5[:3], test_y_1_5[:3]

(array([[ 0.15993359, -1.742     ],
        [ 0.12460938, -0.4744375 ],
        [ 0.21911719, -0.9045    ]]), array([ 1.,  1.,  1.]))

In [105]:
for c in (0.001, 0.01, 0.1, 1):
    print(c)
for c in (0.001,):
    print(c)

0.001
0.01
0.1
1
0.001


In [116]:
for c in (0.0001,0.001,0.01,0.1,1):
    clf = svm.SVC(C=c, decision_function_shape='ovr', kernel='poly', degree=2, gamma=1, coef0=1)
    clf.fit(train_x_1_5, train_y_1_5)
    e_in = (clf.predict(train_x_1_5) != train_y_1_5).sum() / len(train_y_1_5)
    e_out = (clf.predict(test_x_1_5) != test_y_1_5).sum() /len(test_y_1_5)
    print('C=', c, 'E_in=', e_in, '#S.Vec=', clf.n_support_.sum(), 'E_out=', e_out)

C= 0.0001 E_in= 0.00896860986547 #S.Vec= 236 E_out= 0.0165094339623
C= 0.001 E_in= 0.00448430493274 #S.Vec= 76 E_out= 0.0165094339623
C= 0.01 E_in= 0.00448430493274 #S.Vec= 34 E_out= 0.0188679245283
C= 0.1 E_in= 0.00448430493274 #S.Vec= 24 E_out= 0.0188679245283
C= 1 E_in= 0.00320307495195 #S.Vec= 24 E_out= 0.0188679245283


## ^^^ 5. [d]

In [117]:
for c in (0.0001,0.001,0.01,0.1,1):
    clf = svm.SVC(C=c, decision_function_shape='ovr', kernel='poly', degree=5, gamma=1, coef0=1)
    clf.fit(train_x_1_5, train_y_1_5)
    e_in = (clf.predict(train_x_1_5) != train_y_1_5).sum() / len(train_y_1_5)
    e_out = (clf.predict(test_x_1_5) != test_y_1_5).sum() /len(test_y_1_5)
    print('C=', c, 'E_in=', e_in, '#S.Vec=', clf.n_support_.sum(), 'E_out=', e_out)

C= 0.0001 E_in= 0.00448430493274 #S.Vec= 26 E_out= 0.0188679245283
C= 0.001 E_in= 0.00448430493274 #S.Vec= 25 E_out= 0.0212264150943
C= 0.01 E_in= 0.00384368994234 #S.Vec= 23 E_out= 0.0212264150943
C= 0.1 E_in= 0.00320307495195 #S.Vec= 25 E_out= 0.0188679245283
C= 1 E_in= 0.00320307495195 #S.Vec= 21 E_out= 0.0212264150943


## ^^^ 6. [b]

# Cross Validation

In [29]:
test_x_1_5[ix_order][:5]

array([[ 0.19258984, -3.4368125 ],
       [ 0.13055078, -0.3968125 ],
       [ 0.11992383, -0.611375  ],
       [ 0.11573828, -0.4423125 ],
       [ 0.33858789, -4.88225   ]])

In [77]:
n_test = len(test_x_1_5)
entries_per_group = int(n_test/10)
n_hi_groups = n_test - entries_per_group*10
n_per_group = [1+entries_per_group for _ in range(0,n_hi_groups)] + [entries_per_group for _ in range(0,10-n_hi_groups)]
group_indices = np.add.accumulate([0]+n_per_group)
n_test, group_indices

(424, array([  0,  43,  86, 129, 172, 214, 256, 298, 340, 382, 424]))

In [104]:
ix_order = np.random.permutation(n_test)
np.concatenate((ix_order[:43], ix_order[86:]))[:5], ix_order

(array([100,   7,  13, 366, 160]),
 array([100,   7,  13, 366, 160, 207,  51, 395,  10, 420, 387, 364, 164,
         39, 248, 367, 314,  92,  73,  33, 342, 304, 139, 194, 168, 211,
        343, 117,  78, 200, 305, 275, 416, 135, 146, 152, 169, 378, 252,
        178,  34, 316, 246, 286, 227, 134,  89, 308, 390, 156, 154, 292,
        274,  58, 328, 126,  80, 317,  69, 119, 332, 383,  85,   8, 371,
         42, 346,  15,  65,   3, 261,  41,   6, 188,  37, 231, 236, 239,
        203, 214,  50,   4, 103, 136, 133, 393, 407,  53, 102, 348,  62,
        409,  97, 181,  93, 186,   0, 253, 112, 244,  55,  20, 411, 299,
         61, 114, 241, 120, 350, 381, 179, 202, 137, 377, 403, 268, 193,
        423, 374,  87,  83, 388, 234, 298, 285,  21, 391, 107, 116, 243,
         76, 212, 101, 300, 291,  46, 419, 257,  90, 173, 327, 187,  49,
        290, 157, 171, 167, 360, 412, 230,  99,  40,  79,  45, 351, 408,
        224, 353,  66, 223, 113, 337,  94, 270, 330, 369,  27, 397, 158,
        372,  68

In [90]:
ecvs = [5,4,3,3,6]
[0.0001,0.001,0.01,0.1,1][np.argmin(ecvs)]

0.01

In [153]:
def mk_grp_indices(n_data, n_grp=10):
    '''Make a list of indices of group boundaries. It starts with 0 and contains n_grp+1 entries.'''
    entries_per_group = int(n_data/n_grp)
    n_hi_groups = n_data - entries_per_group * n_grp
    n_per_group = [1+entries_per_group for _ in range(0,n_hi_groups)] + [entries_per_group for _ in range(0,n_grp-n_hi_groups)]
    return np.add.accumulate([0]+n_per_group)

# ix_order = np.random.permutation(len(x))
def run_cv(c, x, y, ix_order):
    '''Returns E_cv'''
    n_data = len(x)
    group_indices = mk_grp_indices(len(x))

    ecvs = []
    for i in range(10):
        t_idx = np.concatenate((ix_order[:group_indices[i]], ix_order[group_indices[i+1]:]))
        v_idx = ix_order[group_indices[i]:group_indices[i+1]]
        t_x = x[t_idx]
        t_y = y[t_idx]
        v_x = x[v_idx]
        v_y = y[v_idx]
    
        clf = svm.SVC(C=c, decision_function_shape='ovr', kernel='poly', degree=2, gamma=1, coef0=1)
        clf.fit(t_x, t_y)
        e_v = (clf.predict(v_x) != v_y).sum() / len(v_y)
        ecvs.append(e_v)
    return np.average(ecvs)

In [154]:
Cs = [0.0001,0.001,0.01,0.1,1]

c_count = np.zeros(len(Cs))
e_cv_sums = np.zeros(len(Cs))
for _ in range(100):
    ix_order = np.random.permutation(len(train_x_1_5))
    ecvs = []
    for c in Cs:
        e_cv = run_cv(c, train_x_1_5, train_y_1_5, ix_order)
        ecvs.append(e_cv)
    min_idx = np.argmin(ecvs)
    c_count[min_idx] += 1
    e_cv_sums = e_cv_sums + ecvs
max_idx = np.argmax(c_count)
c_count, Cs[max_idx], e_cv_sums[max_idx]/100

(array([  0.,  48.,  24.,  16.,  12.]), 0.001, 0.0047791115466274637)

## ^^^ 7. [b]

## ^^^ 8. [c]

# RBF Kernel

In [159]:
rbf_Cs = [0.01, 1, 100, 1e4, 1e6]
eins = []
eouts = []
for c in rbf_Cs:
    clf = svm.SVC(C=c, decision_function_shape='ovr', kernel='rbf', gamma=1)
    clf.fit(train_x_1_5, train_y_1_5)
    e_in = (clf.predict(train_x_1_5) != train_y_1_5).sum() / len(train_y_1_5)
    e_out = (clf.predict(test_x_1_5) != test_y_1_5).sum() /len(test_y_1_5)
    eins.append(e_in)
    eouts.append(e_out)
    print('C=', c, 'E_in=', e_in, '#S.Vec=', clf.n_support_.sum(), 'E_out=', e_out)
e_in_min_idx = np.argmin(eins)
print('C=', rbf_Cs[e_in_min_idx], 'has min E_in', eins[e_in_min_idx])
e_out_min_idx = np.argmin(eouts)
print('C=', rbf_Cs[e_out_min_idx], 'has min E_out', eouts[e_out_min_idx])

C= 0.01 E_in= 0.00384368994234 #S.Vec= 403 E_out= 0.0235849056604
C= 1 E_in= 0.00448430493274 #S.Vec= 31 E_out= 0.0212264150943
C= 100 E_in= 0.00320307495195 #S.Vec= 22 E_out= 0.0188679245283
C= 10000.0 E_in= 0.00256245996156 #S.Vec= 20 E_out= 0.0235849056604
C= 1000000.0 E_in= 0.000640614990391 #S.Vec= 17 E_out= 0.0235849056604
C= 1000000.0 has min E_in 0.000640614990391
C= 100 has min E_out 0.0188679245283


## ^^^ 9. [e]

## ^^^ 10. [c]